internal/fwserver: Use response plan value instead of request with nested attributes
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/644
Reference: https://discuss.hashicorp.com/t/framework-v1-1-1-strategies-for-diagnosing-resource-state-churn/49688

The attribute plan modification logic must preserve any changes made by the "top level" list/map/set/single nested attribute plan modifiers before continuing on to nested attributes.

New unit testing failures prior to the logic change:

```
--- FAIL: TestAttributeModifyPlan (0.00s)
    --- FAIL: TestAttributeModifyPlan/attribute-list-nested-usestateforunknown (0.00s)
        attribute_plan_modification_test.go:1107: Unexpected response (-wanted, +got):   fwserver.ModifyAttributePlanResponse{
            - 	AttributePlan:   s`[{"nested_computed":"statevalue1"}]`,
            + 	AttributePlan:   s"[]",
              	Diagnostics:     nil,
              	RequiresReplace: s"[]",
              	Private:         nil,
              }
    --- FAIL: TestAttributeModifyPlan/attribute-map-nested-usestateforunknown (0.00s)
        attribute_plan_modification_test.go:1107: Unexpected response (-wanted, +got):   fwserver.ModifyAttributePlanResponse{
            - 	AttributePlan:   s`{"key1":{"nested_computed":"statevalue1"}}`,
            + 	AttributePlan:   s"{}",
              	Diagnostics:     nil,
              	RequiresReplace: s"[]",
              	Private:         nil,
              }
    --- FAIL: TestAttributeModifyPlan/attribute-single-nested-usestateforunknown (0.00s)
        attribute_plan_modification_test.go:1107: Unexpected response (-wanted, +got):   fwserver.ModifyAttributePlanResponse{
            - 	AttributePlan:   s`{"nested_computed":"statevalue1"}`,
            + 	AttributePlan:   s`{"nested_computed":<unknown>}`,
              	Diagnostics:     nil,
              	RequiresReplace: s"[]",
              	Private:         nil,
              }
    --- FAIL: TestAttributeModifyPlan/attribute-set-nested-usestateforunknown (0.00s)
        attribute_plan_modification_test.go:1107: Unexpected response (-wanted, +got):   fwserver.ModifyAttributePlanResponse{
            - 	AttributePlan:   s`[{"nested_computed":"statevalue1"}]`,
            + 	AttributePlan:   s"[]",
              	Diagnostics:     nil,
              	RequiresReplace: s"[]",
              	Private:         nil,
              }
FAIL
```